(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python$ python run_pose_estimation.py
Traceback (most recent call last):
  File "memryx/runtime/dfp.py", line 46, in memryx.runtime.dfp.Dfp.__init__
FileNotFoundError: [Errno 2] No such file or directory: '../../models/YOLO_v8_medium_pose_640_640_3_onnx.dfp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python/run_pose_estimation.py", line 193, in <module>
    run_mxa(dfp, post_model, app)
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python/run_pose_estimation.py", line 173, in run_mxa
    accl = AsyncAccl(dfp)
           ^^^^^^^^^^^^^^
  File "memryx/runtime/accl.py", line 1480, in memryx.runtime.accl.AsyncAccl.__init__
  File "memryx/runtime/accl.py", line 176, in memryx.runtime.accl.Accl.__init__
  File "memryx/runtime/accl.py", line 302, in memryx.runtime.accl.Accl._parse_dfp
  File "memryx/runtime/dfp.py", line 49, in memryx.runtime.dfp.Dfp.__init__
memryx.errors.UtilityError: Error opening file ../../models/YOLO_v8_medium_pose_640_640_3_onnx.dfp

(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python$ wget https://developer.memryx.com/model_explorer/2p0/YOLO_v8_medium_pose_640_640_3_onnx.zip
mkdir -p models
unzip YOLO_v8_medium_pose_640_640_3_onnx.zip -d models
--2025-10-24 04:01:14--  https://developer.memryx.com/model_explorer/2p0/YOLO_v8_medium_pose_640_640_3_onnx.zip
Resolving developer.memryx.com (developer.memryx.com)... 3.175.130.55, 3.175.130.92, 3.175.130.85, ...
Connecting to developer.memryx.com (developer.memryx.com)|3.175.130.55|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28427445 (27M) [application/zip]
Saving to: ‘YOLO_v8_medium_pose_640_640_3_onnx.zip’

YOLO_v8_medium_pose_640_ 100%[=================================>]  27.11M  6.95MB/s    in 4.4s    

2025-10-24 04:01:19 (6.22 MB/s) - ‘YOLO_v8_medium_pose_640_640_3_onnx.zip’ saved [28427445/28427445]

Archive:  YOLO_v8_medium_pose_640_640_3_onnx.zip
 extracting: models/YOLO_v8_medium_pose_640_640_3_onnx_post.onnx  
 extracting: models/YOLO_v8_medium_pose_640_640_3_onnx.dfp  
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python$ python run_pose_estimation.py -d models -post models
Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python/run_pose_estimation.py", line 193, in <module>
    run_mxa(dfp, post_model, app)
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python/run_pose_estimation.py", line 173, in run_mxa
    accl = AsyncAccl(dfp)
           ^^^^^^^^^^^^^^
  File "memryx/runtime/accl.py", line 1480, in memryx.runtime.accl.AsyncAccl.__init__
  File "memryx/runtime/accl.py", line 176, in memryx.runtime.accl.Accl.__init__
  File "memryx/runtime/accl.py", line 302, in memryx.runtime.accl.Accl._parse_dfp
  File "memryx/runtime/dfp.py", line 44, in memryx.runtime.dfp.Dfp.__init__
memryx.errors.UtilityError: Input file: models is not a .dfp file generated by the NeuralCompiler

(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_es((((((((mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python$ ls
export_model.py
memryx.neural_compiler.log
models
run_pose_estimation.py
YOLO_v8_medium_pose_640_640_3_onnx.dfp
YOLO_v8_medium_pose_640_640_3_onnx.zip
yolov8m-pose_crop.onnx
yolov8m-pose.onnx
yolov8m-pose_post.onnx
yolov8m-pose.pt
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python$ cd ../..
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ ls
assets  LICENSE.md  README.md  src
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ pip install opencv-python==4.11.0.86
Requirement already satisfied: opencv-python==4.11.0.86 in /home/memryx/mx/lib/python3.12/site-packages (4.11.0.86)
Requirement already satisfied: numpy>=1.21.2 in /home/memryx/mx/lib/python3.12/site-packages (from opencv-python==4.11.0.86) (1.26.4)
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ pip install ultralytics==8.3.161
Requirement already satisfied: ultralytics==8.3.161 in /home/memryx/mx/lib/python3.12/site-packages (8.3.161)
Requirement already satisfied: numpy>=1.23.0 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (1.26.4)
Requirement already satisfied: matplotlib>=3.3.0 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (3.9.4)
Requirement already satisfied: opencv-python>=4.6.0 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (11.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (1.13.1)
Requirement already satisfied: torch>=1.8.0 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (2.3.1)
Requirement already satisfied: torchvision>=0.9.0 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (0.18.1)
Requirement already satisfied: tqdm>=4.64.0 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (4.67.1)
Requirement already satisfied: psutil in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (6.0.0)
Requirement already satisfied: py-cpuinfo in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (2.3.3)
Requirement already satisfied: ultralytics-thop>=2.0.0 in /home/memryx/mx/lib/python3.12/site-packages (from ultralytics==8.3.161) (2.0.17)
Requirement already satisfied: contourpy>=1.0.1 in /home/memryx/mx/lib/python3.12/site-packages (from matplotlib>=3.3.0->ultralytics==8.3.161) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/memryx/mx/lib/python3.12/site-packages (from matplotlib>=3.3.0->ultralytics==8.3.161) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/memryx/mx/lib/python3.12/site-packages (from matplotlib>=3.3.0->ultralytics==8.3.161) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/memryx/mx/lib/python3.12/site-packages (from matplotlib>=3.3.0->ultralytics==8.3.161) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /home/memryx/mx/lib/python3.12/site-packages (from matplotlib>=3.3.0->ultralytics==8.3.161) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/memryx/mx/lib/python3.12/site-packages (from matplotlib>=3.3.0->ultralytics==8.3.161) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/memryx/mx/lib/python3.12/site-packages (from matplotlib>=3.3.0->ultralytics==8.3.161) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/memryx/mx/lib/python3.12/site-packages (from pandas>=1.1.4->ultralytics==8.3.161) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/memryx/mx/lib/python3.12/site-packages (from pandas>=1.1.4->ultralytics==8.3.161) (2025.2)
Requirement already satisfied: six>=1.5 in /home/memryx/mx/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics==8.3.161) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/memryx/mx/lib/python3.12/site-packages (from requests>=2.23.0->ultralytics==8.3.161) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/memryx/mx/lib/python3.12/site-packages (from requests>=2.23.0->ultralytics==8.3.161) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/memryx/mx/lib/python3.12/site-packages (from requests>=2.23.0->ultralytics==8.3.161) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/memryx/mx/lib/python3.12/site-packages (from requests>=2.23.0->ultralytics==8.3.161) (2025.1.31)
Requirement already satisfied: filelock in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (3.17.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (4.12.2)
Requirement already satisfied: sympy in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (1.13.3)
Requirement already satisfied: networkx in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (3.2.1)
Requirement already satisfied: jinja2 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (3.1.5)
Requirement already satisfied: fsspec in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (2025.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/memryx/mx/lib/python3.12/site-packages (from torch>=1.8.0->ultralytics==8.3.161) (12.1.105)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/memryx/mx/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.8.0->ultralytics==8.3.161) (12.8.61)
Requirement already satisfied: MarkupSafe>=2.0 in /home/memryx/mx/lib/python3.12/site-packages (from jinja2->torch>=1.8.0->ultralytics==8.3.161) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/memryx/mx/lib/python3.12/site-packages (from sympy->torch>=1.8.0->ultralytics==8.3.161) (1.3.0)
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ wget https://developer.memryx.com/model_explorer/2p0/YOLO_v8_medium_pose_640_640_3_onnx.zip
mkdir -p models
unzip YOLO_v8_medium_pose_640_640_3_onnx.zip -d models
--2025-10-24 04:45:20--  https://developer.memryx.com/model_explorer/2p0/YOLO_v8_medium_pose_640_640_3_onnx.zip
Resolving developer.memryx.com (developer.memryx.com)... 3.175.130.85, 3.175.130.55, 3.175.130.82, ...
Connecting to developer.memryx.com (developer.memryx.com)|3.175.130.85|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28427445 (27M) [application/zip]
Saving to: ‘YOLO_v8_medium_pose_640_640_3_onnx.zip’

YOLO_v8_medium_pose 100%[================>]  27.11M  6.34MB/s    in 4.3s    

2025-10-24 04:45:25 (6.34 MB/s) - ‘YOLO_v8_medium_pose_640_640_3_onnx.zip’ saved [28427445/28427445]

Archive:  YOLO_v8_medium_pose_640_640_3_onnx.zip
 extracting: models/YOLO_v8_medium_pose_640_640_3_onnx_post.onnx  
 extracting: models/YOLO_v8_medium_pose_640_640_3_onnx.dfp  
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ cd src/python/
python run_pose_estimation.py
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
^CQObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python$ python run_pose_estimation.py
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
^CQObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python$ ls -la
total 314680
drwxrwxr-x 3 memryx memryx      4096 Oct 24 04:01 .
drwxrwxr-x 5 memryx memryx      4096 Oct 24 03:43 ..
-rw-rw-r-- 1 memryx memryx       151 Oct 24 03:29 export_model.py
-rw-rw-r-- 1 memryx memryx      7267 Oct 24 03:37 memryx.neural_compiler.log
drwxrwxr-x 2 memryx memryx      4096 Oct 24 04:01 models
-rw-rw-r-- 1 memryx memryx      8890 Oct 24 02:54 run_pose_estimation.py
-rw-rw-r-- 1 memryx memryx  28152433 Oct 24 03:37 YOLO_v8_medium_pose_640_640_3_onnx.dfp
-rw-rw-r-- 1 memryx memryx  28427445 Sep 22 11:20 YOLO_v8_medium_pose_640_640_3_onnx.zip
-rw-rw-r-- 1 memryx memryx 105887692 Oct 24 03:31 yolov8m-pose_crop.onnx
-rw-rw-r-- 1 memryx memryx 106166877 Oct 24 03:30 yolov8m-pose.onnx
-rw-rw-r-- 1 memryx memryx    278709 Oct 24 03:31 yolov8m-pose_post.onnx
-rw-rw-r-- 1 memryx memryx  53266977 Oct 24 03:30 yolov8m-pose.pt
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/src/python$ cd ../..
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ git clone https://githup.com/thee1444/m.git
Cloning into 'm'...
fatal: unable to update url base from redirection:
  asked for: https://githup.com/thee1444/m.git/info/refs?service=git-upload-pack
   redirect: https://ar.shein.com/?url_from=CMV&affiliateID=02&click_id=e78e1d98e66e47f6979aaee62bd9867b&cdn_rsite=ak&ref=www&rep=dir&ret=ar
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ git clone https://githup.com/thee1444/m
Cloning into 'm'...
fatal: unable to update url base from redirection:
  asked for: https://githup.com/thee1444/m/info/refs?service=git-upload-pack
   redirect: https://ar.shein.com/?url_from=CMV&affiliateID=02&click_id=8f0fe2c5c31b41cbb9a43f96d569b704&cdn_rsite=ak&ref=www&rep=dir&ret=ar
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ 
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ ls -la
total 27840
drwxrwxr-x  5 memryx memryx     4096 Oct 24 06:45 .
drwxrwxr-x 17 memryx memryx     4096 Oct 24 02:54 ..
drwxrwxr-x  2 memryx memryx     4096 Oct 24 02:55 assets
-rw-rw-r--  1 memryx memryx    10587 Oct 24 06:45 data_extraction_memFramwork.py
-rw-rw-r--  1 memryx memryx    32706 Oct 24 02:54 LICENSE.md
drwxrwxr-x  2 memryx memryx     4096 Oct 24 04:45 models
-rw-rw-r--  1 memryx memryx     8575 Oct 24 02:54 README.md
drwxrwxr-x  5 memryx memryx     4096 Oct 24 03:43 src
-rw-rw-r--  1 memryx memryx 28427445 Sep 22 11:20 YOLO_v8_medium_pose_640_640_3_onnx.zip
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python data_extraction_memFramework
python: can't open file '/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramework': [Errno 2] No such file or directory
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python data_extraction_memFramework.py
python: can't open file '/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramework.py': [Errno 2] No such file or directory
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python data_extraction_memFramwork.py
Traceback (most recent call last):
  File "memryx/runtime/dfp.py", line 46, in memryx.runtime.dfp.Dfp.__init__
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/yolov8_pose.dfp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 300, in <module>
    main()
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 286, in main
    extractor = FallDataExtractor(
                ^^^^^^^^^^^^^^^^^^
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 24, in __init__
    self.accl = AsyncAccl(model_path)
                ^^^^^^^^^^^^^^^^^^^^^
  File "memryx/runtime/accl.py", line 1480, in memryx.runtime.accl.AsyncAccl.__init__
  File "memryx/runtime/accl.py", line 176, in memryx.runtime.accl.Accl.__init__
  File "memryx/runtime/accl.py", line 302, in memryx.runtime.accl.Accl._parse_dfp
  File "memryx/runtime/dfp.py", line 49, in memryx.runtime.dfp.Dfp.__init__
memryx.errors.UtilityError: Error opening file path/to/yolov8_pose.dfp

(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python data_extraction_memFramwork.py
Traceback (most recent call last):
  File "memryx/runtime/dfp.py", line 46, in memryx.runtime.dfp.Dfp.__init__
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/yolov8_pose.dfp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 300, in <module>
    main()
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 286, in main
    extractor = FallDataExtractor(
                ^^^^^^^^^^^^^^^^^^
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 24, in __init__
    self.accl = AsyncAccl(model_path)
                ^^^^^^^^^^^^^^^^^^^^^
  File "memryx/runtime/accl.py", line 1480, in memryx.runtime.accl.AsyncAccl.__init__
  File "memryx/runtime/accl.py", line 176, in memryx.runtime.accl.Accl.__init__
  File "memryx/runtime/accl.py", line 302, in memryx.runtime.accl.Accl._parse_dfp
  File "memryx/runtime/dfp.py", line 49, in memryx.runtime.dfp.Dfp.__init__
memryx.errors.UtilityError: Error opening file path/to/yolov8_pose.dfp

(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python data_extraction_memFramwork.py
Traceback (most recent call last):
  File "memryx/runtime/dfp.py", line 46, in memryx.runtime.dfp.Dfp.__init__
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/yolov8_pose.dfp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 300, in <module>
    main()
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 286, in main
    extractor = FallDataExtractor(
                ^^^^^^^^^^^^^^^^^^
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 24, in __init__
    self.accl = AsyncAccl(model_path)
                ^^^^^^^^^^^^^^^^^^^^^
  File "memryx/runtime/accl.py", line 1480, in memryx.runtime.accl.AsyncAccl.__init__
  File "memryx/runtime/accl.py", line 176, in memryx.runtime.accl.Accl.__init__
  File "memryx/runtime/accl.py", line 302, in memryx.runtime.accl.Accl._parse_dfp
  File "memryx/runtime/dfp.py", line 49, in memryx.runtime.dfp.Dfp.__init__
memryx.errors.UtilityError: Error opening file path/to/yolov8_pose.dfp

(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ nano data_extraction_memFramwork.py
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python data_extraction_memFramwork.py
Scene Home not found, skipping...
Scene Coffee_room not found, skipping...
Scene Office not found, skipping...
Scene Lecture_room not found, skipping...

Total sequences extracted: 0
  Falls: 0
  Normal: 0
Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 300, in <module>
    main()
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 292, in main
    X, y = extractor.process_dataset(DATASET_ROOT, OUTPUT_FILE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 243, in process_dataset
    print(f"  Feature dimension: {X.shape[1]}")
                                  ~~~~~~~^^^
IndexError: tuple index out of range
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python data_extraction.py
============================================================
FALL DETECTION DATA EXTRACTION
Using YOLOv8 Pose (No MemryX Hardware Required)
============================================================
Loading YOLOv8 Pose model: yolov8m-pose.pt
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m-pose.pt to 'yolov8m-pose.pt'...
100%|███████████████████████████████████| 50.8M/50.8M [00:14<00:00, 3.68MB/s]
Model loaded successfully!
Scene 'Home' not found, skipping...
Scene 'Coffee_room' not found, skipping...
Scene 'Office' not found, skipping...
Scene 'Lecture_room' not found, skipping...

⚠ WARNING: No sequences were extracted!
Please check your dataset path and structure.

✗ Extraction failed. Please check your dataset path.
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python data_extraction_memFramwork.py
Scene Home not found, skipping...
Scene Coffee_room not found, skipping...
Scene Office not found, skipping...
Scene Lecture_room not found, skipping...

Total sequences extracted: 0
  Falls: 0
  Normal: 0
Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 300, in <module>
    main()
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 292, in main
    X, y = extractor.process_dataset(DATASET_ROOT, OUTPUT_FILE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/data_extraction_memFramwork.py", line 243, in process_dataset
    print(f"  Feature dimension: {X.shape[1]}")
                                  ~~~~~~~^^^
IndexError: tuple index out of range
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ nano data_extraction_memFramwork.py
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ ls -la
total 108360
drwxrwxr-x  6 memryx memryx     4096 Oct 24 08:59 .
drwxrwxr-x 17 memryx memryx     4096 Oct 24 02:54 ..
drwxrwxr-x  2 memryx memryx     4096 Oct 24 02:55 assets
-rw-rw-r--  1 memryx memryx    10580 Oct 24 06:50 data_extraction_memFramwork.py
-rw-rw-r--  1 memryx memryx    16030 Oct 24 06:52 data_extraction.py
drwxrwxr-x  4 memryx memryx     4096 Oct 24 07:12 le2i_dataset
-rw-rw-r--  1 memryx memryx    32706 Oct 24 02:54 LICENSE.md
-rw-rw-r--  1 memryx memryx   977400 Oct 24 08:59 model.h5
drwxrwxr-x  2 memryx memryx     4096 Oct 24 06:54 models
-rw-rw-r--  1 memryx memryx     8575 Oct 24 02:54 README.md
drwxrwxr-x  5 memryx memryx     4096 Oct 24 03:43 src
-rw-rw-r--  1 memryx memryx 28427445 Sep 22 11:20 YOLO_v8_medium_pose_640_640_3_onnx.zip
-rw-rw-r--  1 memryx memryx 53266977 Oct 24 06:52 yolov8m-pose.pt
-rw-r--r--  1 memryx memryx 28183853 Jul 16 23:27 yolov8_pose.dfp
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python -m tf2onnx.convert --saved-model my_model.h5 --output my_model.onnx --opset13
2025-10-24 09:01:47.776966: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-24 09:01:47.787445: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-24 09:01:47.790536: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-24 09:01:47.798624: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-24 09:01:48.497790: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
<frozen runpy>:128: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
usage: convert.py [-h] [--input INPUT] [--graphdef GRAPHDEF]
                  [--saved-model SAVED_MODEL] [--tag TAG]
                  [--signature_def SIGNATURE_DEF]
                  [--concrete_function CONCRETE_FUNCTION]
                  [--checkpoint CHECKPOINT] [--keras KERAS]
                  [--tflite TFLITE] [--tfjs TFJS] [--large_model]
                  [--output OUTPUT] [--inputs INPUTS] [--outputs OUTPUTS]
                  [--ignore_default IGNORE_DEFAULT]
                  [--use_default USE_DEFAULT]
                  [--rename-inputs RENAME_INPUTS]
                  [--rename-outputs RENAME_OUTPUTS] [--use-graph-names]
                  [--opset OPSET] [--dequantize] [--custom-ops CUSTOM_OPS]
                  [--extra_opset EXTRA_OPSET]
                  [--load_op_libraries LOAD_OP_LIBRARIES]
                  [--target {rs4,rs5,rs6,caffe2,tensorrt,nhwc}]
                  [--continue_on_error] [--verbose] [--debug]
                  [--output_frozen_graph OUTPUT_FROZEN_GRAPH]
                  [--inputs-as-nchw INPUTS_AS_NCHW]
                  [--outputs-as-nchw OUTPUTS_AS_NCHW]
convert.py: error: unrecognized arguments: --opset13
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python -m tf2onnx.convert --saved-model my_model.h5 --output my_model.onnx --opset 13
2025-10-24 09:01:58.524989: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-24 09:01:58.535227: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-24 09:01:58.538209: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-24 09:01:58.545706: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-24 09:01:59.256176: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
<frozen runpy>:128: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
2025-10-24 09:02:00,169 - WARNING - ***IMPORTANT*** Installed protobuf is not cpp accelerated. Conversion will be extremely slow. See https://github.com/onnx/tensorflow-onnx/issues/1557
2025-10-24 09:02:00,220 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 714, in <module>
    main()
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 242, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 636, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 570, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: my_model.h5/{saved_model.pbtxt|saved_model.pb}
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python -m tf2onnx.convert --saved-model model.h5 --output my_model.onnx --opset 13
2025-10-24 09:02:15.727324: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-24 09:02:15.737661: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-24 09:02:15.740745: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-24 09:02:15.748071: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-24 09:02:16.450457: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
<frozen runpy>:128: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
2025-10-24 09:02:17,333 - WARNING - ***IMPORTANT*** Installed protobuf is not cpp accelerated. Conversion will be extremely slow. See https://github.com/onnx/tensorflow-onnx/issues/1557
2025-10-24 09:02:17,335 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 714, in <module>
    main()
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 242, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 636, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 570, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: model.h5/{saved_model.pbtxt|saved_model.pb}
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ pip install tensorflow onnx tf2onnx
Requirement already satisfied: tensorflow in /home/memryx/mx/lib/python3.12/site-packages (2.17.1)
Requirement already satisfied: onnx in /home/memryx/mx/lib/python3.12/site-packages (1.16.2)
Requirement already satisfied: tf2onnx in /home/memryx/mx/lib/python3.12/site-packages (1.16.1)
Requirement already satisfied: absl-py>=1.0.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (25.1.24)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: libclang>=13.0.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (0.4.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (75.8.0)
Requirement already satisfied: six>=1.12.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (1.70.0)
Requirement already satisfied: tensorboard<2.18,>=2.17 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (2.17.1)
Requirement already satisfied: keras>=3.2.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (3.6.0)
Requirement already satisfied: numpy<2.0.0,>=1.26.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorflow) (1.26.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/memryx/mx/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/memryx/mx/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/memryx/mx/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/memryx/mx/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2025.1.31)
Requirement already satisfied: markdown>=2.6.8 in /home/memryx/mx/lib/python3.12/site-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/memryx/mx/lib/python3.12/site-packages (from tensorboard<2.18,>=2.17->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /home/memryx/mx/lib/python3.12/site-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/memryx/mx/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /home/memryx/mx/lib/python3.12/site-packages (from keras>=3.2.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /home/memryx/mx/lib/python3.12/site-packages (from keras>=3.2.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in /home/memryx/mx/lib/python3.12/site-packages (from keras>=3.2.0->tensorflow) (0.14.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/memryx/mx/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/memryx/mx/lib/python3.12/site-packages (from rich->keras>=3.2.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/memryx/mx/lib/python3.12/site-packages (from rich->keras>=3.2.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /home/memryx/mx/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow) (0.1.2)
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python -m tf2onnx.convert --saved-model model.h5 --output my_model.onnx --opset 13
2025-10-24 09:05:05.815142: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-24 09:05:05.825596: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-24 09:05:05.828778: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-24 09:05:05.836426: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-24 09:05:06.541202: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
<frozen runpy>:128: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
2025-10-24 09:05:07,414 - WARNING - ***IMPORTANT*** Installed protobuf is not cpp accelerated. Conversion will be extremely slow. See https://github.com/onnx/tensorflow-onnx/issues/1557
2025-10-24 09:05:07,416 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 714, in <module>
    main()
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 242, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 636, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 570, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: model.h5/{saved_model.pbtxt|saved_model.pb}
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mkdir SavedModel
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python -m tf2onnx.convert --saved-model model.h5 --output my_model.onnx --opset 13
2025-10-24 09:05:27.326956: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-24 09:05:27.337282: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-24 09:05:27.340744: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-24 09:05:27.348173: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-24 09:05:28.051599: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
<frozen runpy>:128: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
2025-10-24 09:05:28,929 - WARNING - ***IMPORTANT*** Installed protobuf is not cpp accelerated. Conversion will be extremely slow. See https://github.com/onnx/tensorflow-onnx/issues/1557
2025-10-24 09:05:28,931 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 714, in <module>
    main()
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 242, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 636, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 570, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: model.h5/{saved_model.pbtxt|saved_model.pb}
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python -m tf2onnx.convert --saved-model model.h5 --output my_model.onnx --opset 13
2025-10-24 09:18:32.742844: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-24 09:18:32.752428: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-24 09:18:32.755311: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-24 09:18:32.763439: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-24 09:18:33.469704: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
<frozen runpy>:128: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
2025-10-24 09:18:34,342 - WARNING - ***IMPORTANT*** Installed protobuf is not cpp accelerated. Conversion will be extremely slow. See https://github.com/onnx/tensorflow-onnx/issues/1557
2025-10-24 09:18:34,344 - WARNING - '--tag' not specified for saved_model. Using --tag serve
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 714, in <module>
    main()
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/convert.py", line 242, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 636, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,
  File "/home/memryx/mx/lib/python3.12/site-packages/tf2onnx/tf_loader.py", line 570, in _from_saved_model_v2
    imported = tf.saved_model.load(model_path, tags=tag)  # pylint: disable=no-value-for-parameter
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: model.h5/{saved_model.pbtxt|saved_model.pb}
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python -m tf2onnx.convert --saved-model saved_model --output my_model.onnx --opset 13
2025-10-24 09:19:19.122221: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-24 09:19:19.132308: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-10-24 09:19:19.135517: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-24 09:19:19.142815: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-24 09:19:19.850675: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
<frozen runpy>:128: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
2025-10-24 09:19:20,794 - WARNING - ***IMPORTANT*** Installed protobuf is not cpp accelerated. Conversion will be extremely slow. See https://github.com/onnx/tensorflow-onnx/issues/1557
2025-10-24 09:19:20,796 - WARNING - '--tag' not specified for saved_model. Using --tag serve
2025-10-24 09:19:21,177 - INFO - Signatures found in model: [serve,serving_default].
2025-10-24 09:19:21,177 - WARNING - '--signature_def' not specified, using first signature: serve
2025-10-24 09:19:21,177 - INFO - Output names: ['output_0']
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1761311961.195778   29836 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2025-10-24 09:19:21.195931: I tensorflow/core/grappler/clusters/single_machine.cc:361] Starting new session
I0000 00:00:1761311961.355095   29836 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2025-10-24 09:19:21.355202: I tensorflow/core/grappler/clusters/single_machine.cc:361] Starting new session
2025-10-24 09:19:21,377 - INFO - Using tensorflow=2.17.1, onnx=1.16.2, tf2onnx=1.16.1/15c810
2025-10-24 09:19:21,377 - INFO - Using opset <onnx, 13>
2025-10-24 09:19:21,395 - INFO - Computed 0 values for constant folding
2025-10-24 09:19:21,428 - INFO - Optimizing ONNX model
2025-10-24 09:19:21,503 - INFO - After optimization: Cast -1 (1->0), Identity -2 (2->0), Transpose -23 (24->1)
2025-10-24 09:19:21,507 - INFO - 
2025-10-24 09:19:21,507 - INFO - Successfully converted TensorFlow model saved_model to ONNX
2025-10-24 09:19:21,507 - INFO - Model inputs: ['inputs']
2025-10-24 09:19:21,507 - INFO - Model outputs: ['output_0']
2025-10-24 09:19:21,507 - INFO - ONNX model is saved at my_model.onnx
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile \
>  --input my_model.onnx
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: ambiguous option: --input could match --input_shapes, --input_format, --input_data_range, --inputs
^C
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile \ --input my_model.onnx
^CTraceback (most recent call last):
  File "/home/memryx/mx/bin/mx_nc", line 5, in <module>
    from memryx.neural_compiler.nc import main
  File "memryx/__init__.py", line 2, in init memryx
  File "memryx/neural_compiler/nc.py", line 69, in init memryx.neural_compiler.nc
  File "memryx/neural_compiler/graph/__init__.py", line 2, in init memryx.neural_compiler.graph
  File "memryx/neural_compiler/graph/engine/graph_engine.py", line 41, in init memryx.neural_compiler.graph.engine.graph_engine
  File "memryx/utilities/printing.py", line 68, in memryx.utilities.printing.silence_tensorflow
  File "/home/memryx/mx/lib/python3.12/site-packages/tensorflow/__init__.py", line 464, in <module>
    importlib.import_module("keras.src.optimizers")
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/__init__.py", line 4, in <module>
    from keras.api import DTypePolicy
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import activations
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/api/activations/__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/activations/__init__.py", line 22, in <module>
    from keras.src.saving import object_registration
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/saving/__init__.py", line 7, in <module>
    from keras.src.saving.saving_api import load_model
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/saving/saving_api.py", line 7, in <module>
    from keras.src.legacy.saving import legacy_h5_format
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/legacy/saving/legacy_h5_format.py", line 13, in <module>
    from keras.src.legacy.saving import saving_utils
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/legacy/saving/saving_utils.py", line 10, in <module>
    from keras.src import models
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/models/__init__.py", line 1, in <module>
    from keras.src.models.functional import Functional
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/models/functional.py", line 16, in <module>
    from keras.src.models.model import Model
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/models/model.py", line 12, in <module>
    from keras.src.trainers import trainer as base_trainer
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/trainers/trainer.py", line 14, in <module>
    from keras.src.trainers.data_adapters import data_adapter_utils
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/trainers/data_adapters/__init__.py", line 4, in <module>
    from keras.src.trainers.data_adapters import array_data_adapter
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/trainers/data_adapters/array_data_adapter.py", line 7, in <module>
    from keras.src.trainers.data_adapters import array_slicing
  File "/home/memryx/mx/lib/python3.12/site-packages/keras/src/trainers/data_adapters/array_slicing.py", line 11, in <module>
    import pandas
  File "/home/memryx/mx/lib/python3.12/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/memryx/mx/lib/python3.12/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/home/memryx/mx/lib/python3.12/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/memryx/mx/lib/python3.12/site-packages/pandas/_libs/tslibs/__init__.py", line 39, in <module>
    from pandas._libs.tslibs import dtypes  # pylint: disable=import-self
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 645, in parent
KeyboardInterrupt

(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile \
> --input my_model.onnx \
> --output my_model.dfp \
> -- target mx3 \
> --quantize int8 \
> --optimize perf
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: ambiguous option: --input could match --input_shapes, --input_format, --input_data_range, --inputs
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile --input my_model.onnx --output my_model.dfp -- target mx3 --quantize int8 --optimize perf
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: ambiguous option: --input could match --input_shapes, --input_format, --input_data_range, --inputs
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile --input my_model.onnx --output my_model.dfp -- target mx3
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: ambiguous option: --input could match --input_shapes, --input_format, --input_data_range, --inputs
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile --input my_model.onnx --output my_model.dfp --target mx3 --quantize int8 --optimize perf
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: ambiguous option: --input could match --input_shapes, --input_format, --input_data_range, --inputs
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile --input my_model.onnx --output my_model.dfp
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: ambiguous option: --input could match --input_shapes, --input_format, --input_data_range, --inputs
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile --model_in my_model.onnx --dfp_fname my_model.dfp --target mx3 --quantize int8 --optimize perf
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: ambiguous option: --optimize could match --optimize_wmem_gbf, --optimizer_cost_margin
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile --model_in my_model.onnx --dfp_fname my_model.dfp --target mx3 --quantize int8
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: unrecognized arguments: compile --quantize int8
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile --model_in my_model.onnx --dfp_fname my_model.dfp --target mx3
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: unrecognized arguments: compile
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile --model_in my_model.onnx --dfp_fname my_model.dfp
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: unrecognized arguments: compile
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile -v -m my_model.onnx --dfp_fname my_model.dfp
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: unrecognized arguments: compile
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc compile -v -m my_model.onnx
Usage: mx_nc [-h] [--version] [-c] [-m  [...]] [-is  [...]] [--dfp_fname]
             [--sim_dfp] [-so] [-v] [-bt] [--exp_auto_dp] [-hpoc  [...]]
             [-hpoc_file] [--autocrop] [--model_in_out] [--inputs]
             [--outputs] [--extensions EXTENSIONS [EXTENSIONS ...]]
             [--allow_unsigned_extensions] [-e] [-j] [--target_fps]
             [-ll {debug,info,warning,error,critical}] [-lf LOG_FILE]
mx_nc: error: unrecognized arguments: compile
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc -v -m my_model.onnx

╭─────────────────┬─────┬─────┬────────╮
│                 │     │     │        │
│                 │           ├────    │
│     │     │     ╞══       ══╡        │
│     │     │     │           ├────    │
│     │     │     │     │     │        │
╰─────┴─────┴─────┴─────┴─────┴────────╯

╔══════════════════════════════════════╗
║            Neural Compiler           ║
║  Copyright (c) 2019-2025 MemryX Inc. ║
╚══════════════════════════════════════╝

════════════════════════════════════════
Converting Model   : (Done)                  
Optimizing Graph   : (Done)                  
Warnings raised during Model Conversion / Graph Optimization:
MxUserWarning: GraphConverter::OnnxInterface::Symbolic shape in input 'inputs' is not supported. Setting symbol unk__57 to 1. 
MxUserWarning: GraphConverter::OnnxInterface::Symbolic shape in input 'inputs' is not supported. Setting symbol unk__57 to 1. 
Cores Optimization : (Done)                 
Flow Optimization  : (Done)                 
. . . . . . . . . . . . . . . . . . . . 
Ports Mapping      : (Done)                 
MPU 0 input  port 0: {'model_index': 0, 'layer_name': 'inputs', 'shape': [96, 96, 1, 3]}
MPU 3 output port 0: {'model_index': 0, 'layer_name': 'output_0', 'shape': [1, 1, 1, 1]}
────────────────────────────────────────
Assembling DFP     : (Done)                  
════════════════════════════════════════
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ ls
 assets                           my_model.onnx
 data_extraction_memFramwork.py   README.md
 data_extraction.py               saved_model
 le2i_dataset                     SavedModel
 LICENSE.md                      'saved_model cnn'
 memryx.neural_compiler.log       src
 model.h5                         YOLO_v8_medium_pose_640_640_3_onnx.zip
 models                           yolov8m-pose.pt
 my_model.dfp                     yolov8_pose.dfp
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ acclBench -d my_model.dfp 
*************************************************
*      Evaluate dfp performance using MX3       *
*************************************************

Number of chips the dfp is compiled for = 4

     Model    Stream            FPS
-----------------------------------
         0         0        10438.6

    Device       Temp (C)
-------------------------
         0           34.0
Average FPS per stream : 10438.6
Average FPS for DFP    : 10438.6


 Bench for 1 Model(s) Done 
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ mx_nc -v -m my_model.onnx facerecog.onnx vest.onnx fall.onnx

╭─────────────────┬─────┬─────┬────────╮
│                 │     │     │        │
│                 │           ├────    │
│     │     │     ╞══       ══╡        │
│     │     │     │           ├────    │
│     │     │     │     │     │        │
╰─────┴─────┴─────┴─────┴─────┴────────╯

╔══════════════════════════════════════╗
║            Neural Compiler           ║
║  Copyright (c) 2019-2025 MemryX Inc. ║
╚══════════════════════════════════════╝

════════════════════════════════════════
Traceback (most recent call last):
  File "/home/memryx/mx/bin/mx_nc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "memryx/neural_compiler/nc.py", line 2178, in memryx.neural_compiler.nc.main
  File "memryx/neural_compiler/nc.py", line 1420, in memryx.neural_compiler.nc.NeuralCompiler.run
  File "memryx/neural_compiler/nc.py", line 1399, in memryx.neural_compiler.nc.NeuralCompiler.run
  File "memryx/neural_compiler/nc.py", line 1464, in memryx.neural_compiler.nc.NeuralCompiler.load
  File "memryx/neural_compiler/graph/framework/model_loader_factory.py", line 447, in memryx.neural_compiler.graph.framework.model_loader_factory.ModelLoader.load
  File "memryx/neural_compiler/graph/framework/model_loader_factory.py", line 444, in memryx.neural_compiler.graph.framework.model_loader_factory.ModelLoader.load
FileNotFoundError: [Errno 2] No such file or directory: '/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/facerecog.onnx'
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ nano testCNN.py
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python testCNN.py
Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/testCNN.py", line 3, in <module>
    from memryx import Engine
ImportError: cannot import name 'Engine' from 'memryx' (/home/memryx/mx/lib/python3.12/site-packages/memryx/__init__.cpython-312-x86_64-linux-gnu.so)
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ run testCNN.py
Command 'run' not found, did you mean:
  command 'rue' from snap darkdimension-rue (1.0.7)
  command 'bun' from snap bun-js (1.2.22)
  command 'rn' from deb trn4 (4.0-test77-16)
  command 'grun' from deb grun (0.9.3+git20200303-3)
  command 'runq' from deb exim4-daemon-heavy (4.97-4ubuntu4.3)
  command 'runq' from deb exim4-daemon-light (4.97-4ubuntu4.3)
  command 'runq' from deb sendmail-bin (8.17.2-1)
  command 'zrun' from deb moreutils (0.67-1)
  command 'crun' from deb crun (1.12-1)
  command 'rup' from deb rstat-client (4.0.1-11)
  command 'srun' from deb slurm-client (23.02.6-1ubuntu2)
  command 'runc' from deb runc (1.2.5-0ubuntu1~24.04.1)
  command 'zun' from deb python3-zunclient (4.7.0-0ubuntu1)
See 'snap info <snapname>' for additional versions.
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python3 testCNN.py
Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/testCNN.py", line 3, in <module>
    from memryx import Engine
ImportError: cannot import name 'Engine' from 'memryx' (/home/memryx/mx/lib/python3.12/site-packages/memryx/__init__.cpython-312-x86_64-linux-gnu.so)
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python testCNN.py
Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/testCNN.py", line 3, in <module>
    from memryx import Accelator
ImportError: cannot import name 'Accelator' from 'memryx' (/home/memryx/mx/lib/python3.12/site-packages/memryx/__init__.cpython-312-x86_64-linux-gnu.so)
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python testCNN.py
Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/testCNN.py", line 3, in <module>
    from memryx import Accelerator
ImportError: cannot import name 'Accelerator' from 'memryx' (/home/memryx/mx/lib/python3.12/site-packages/memryx/__init__.cpython-312-x86_64-linux-gnu.so)
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ 
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ nano testimgCNN.py
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ python testimgCNN.py
Traceback (most recent call last):
  File "/home/memryx/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/testimgCNN.py", line 1, in <module>
    from memryx import Engine
ImportError: cannot import name 'Engine' from 'memryx' (/home/memryx/mx/lib/python3.12/site-packages/memryx/__init__.cpython-312-x86_64-linux-gnu.so)
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ ls
 assets                           README.md
 data_extraction_memFramwork.py   saved_model
 data_extraction.py               SavedModel
 fall_model.jpg                  'saved_model cnn'
 le2i_dataset                     src
 LICENSE.md                       testCNN.py
 memryx.neural_compiler.log       testimgCNN.py
 model.h5                         testVest
 models                           YOLO_v8_medium_pose_640_640_3_onnx.zip
 my_model.dfp                     yolov8m-pose.pt
 my_model.onnx                    yolov8_pose.dfp
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8$ cd testVest
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/testVest$ mx_nc -v -m yolov8nForVest.pt

╭─────────────────┬─────┬─────┬────────╮
│                 │     │     │        │
│                 │           ├────    │
│     │     │     ╞══       ══╡        │
│     │     │     │           ├────    │
│     │     │     │     │     │        │
╰─────┴─────┴─────┴─────┴─────┴────────╯

╔══════════════════════════════════════╗
║            Neural Compiler           ║
║  Copyright (c) 2019-2025 MemryX Inc. ║
╚══════════════════════════════════════╝

════════════════════════════════════════
memryx.errors.CompilerError: Unsupported model extension: ".pt"

(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/testVest$ 
(mx) memryx@memryxPC:~/Desktop/memryx_examples/video_inference/pose_estimation_yolov8/testVest$ 

